apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://raw.githubusercontent.com/argoproj/argo-cd/v2.10.7/manifests/install.yaml

patchesStrategicMerge:
  - overlays/nodeport.yaml
  - overlays/configmap.yaml
  - overlays/redis.yaml

namespace: argocd

