# define secret for in-cluster to work with appset cluster generator
# https://github.com/argoproj/applicationset/pull/116
# https://github.com/argoproj/applicationset/issues/35
apiVersion: v1
kind: Secret
metadata:
  labels:
    argocd.argoproj.io/secret-type: cluster
    cluster.name: in-cluster
  name: cluster-local
stringData:
  config: '{"bearerToken":"","tlsClientConfig":{"insecure":false,"caData":""}}'
  name: in-cluster
  server: https://kubernetes.default.svc
type: Opaque
